export const CHAT_TOPICS = [
  'price',
  'area',
  'access',
  'building',
  'location',
  'status',
] as const
export type ChatTopic = (typeof CHAT_TOPICS)[number]
export type ChatLocale = 'ja' | 'en' | 'zh-TW' | 'zh-CN'

const copies = {
  ja: {
    title: '物件情報の自動回答',
    subtitle: '公開されている物件情報から自動回答します。',
    welcome: '価格・広さ・駅までの距離など、この物件について質問できます。',
    placeholder: '例：価格と建物面積を教えて',
    send: '送信',
    clear: '会話をクリア',
    question: 'この物件への質問',
    working: '公開情報を確認しています…',
    inquiry: '内見・詳しい相談へ',
    source: '参照：この物件の公開情報',
    privacy:
      '会話はこのページ内のみ。担当者への連絡は専用チャットから送信できます。',
    unknown: '公開情報に記載がありません。',
    fallback:
      '公開情報から確認できません。価格・面積・駅・築年などについて質問できます。詳しい確認はお問い合わせからご相談ください。',
    restricted:
      '詳しい住所や社内資料はチャットでは案内できません。必要な情報はお問い合わせからご相談ください。',
    confirmation:
      '内見日程、価格交渉、購入条件、融資や許認可は公開情報だけでは確定できません。お問い合わせからご希望をお知らせください。まだ予約・連絡は送信していません。',
    error: '回答を取得できませんでした。もう一度お試しください。',
    rate: '質問が続いています。少し待ってからお試しください。',
    unavailable: 'この物件の公開が終了したため、チャットを利用できません。',
    propertyType: '物件種別',
    builtYear: '築年',
    structure: '構造',
    floorCount: '階数',
    price: '掲載価格',
    buildingArea: '建物面積',
    landArea: '土地面積',
    access: '駅・アクセス',
    building: '築年・建物',
    location: '公開住所',
    status: '現況',
    year: '年',
    floors: '階建て',
    walk: '徒歩',
    minutes: '分',
    suggestions: [
      '価格と面積は？',
      '駅まで徒歩何分？',
      '築年と構造は？',
      '内見を相談したい',
    ],
  },
  en: {
    title: 'Property facts assistant',
    subtitle: 'Automatic answers from the published property facts.',
    welcome:
      'Ask about this property’s price, size, station access or building.',
    placeholder: 'e.g. What are the price and building area?',
    send: 'Send',
    clear: 'Clear conversation',
    question: 'Question about this property',
    working: 'Checking published facts…',
    inquiry: 'Viewing & further questions',
    source: 'Source: this property’s published facts',
    privacy:
      'This conversation stays on this page. Contact the team through the private chat.',
    unknown: 'Not stated in the published facts.',
    fallback:
      'The published facts do not answer this question. Ask about price, area, station access or the building, or use the private chat for further confirmation.',
    restricted:
      'Detailed addresses and internal documents are not provided in this chat. Please use the private chat for the information you need.',
    confirmation:
      'Viewing dates, negotiation, purchase terms, financing and licences require confirmation beyond the published facts. Tell us your request through the private chat. No booking or message has been sent.',
    error: 'We could not load an answer. Please try again.',
    rate: 'Please wait a little before asking another question.',
    unavailable:
      'This property is no longer publicly available, so chat is unavailable.',
    propertyType: 'Property type',
    builtYear: 'Built',
    structure: 'Structure',
    floorCount: 'Floors',
    price: 'Listed asking price',
    buildingArea: 'Building area',
    landArea: 'Land area',
    access: 'Station access',
    building: 'Year & building',
    location: 'Public address',
    status: 'Current status',
    year: '',
    floors: 'floors',
    walk: 'Walk',
    minutes: 'min',
    suggestions: [
      'What are the price and area?',
      'Which station and how long is the walk?',
      'When was it built and what is the structure?',
      'I would like to arrange a viewing',
    ],
  },
  'zh-TW': {
    title: '房產資訊自動回答',
    subtitle: '依據已公開的房產資訊自動回答。',
    welcome: '可以詢問這間房產的價格、面積、車站距離或建築資訊。',
    placeholder: '例如：價格與建築面積是多少？',
    send: '送出',
    clear: '清除對話',
    question: '關於這間房產的問題',
    working: '正在確認公開資訊…',
    inquiry: '看房與詳細諮詢',
    source: '參考：這間房產的公開資訊',
    privacy: '對話僅保留於本頁。聯絡團隊請使用專用聊天。',
    unknown: '公開資訊未載明。',
    fallback:
      '公開資訊無法確認這個問題。可以詢問價格、面積、車站與建築資訊；其他問題請透過專用聊天確認。',
    restricted: '聊天不提供詳細門牌或內部文件。所需資訊請透過專用聊天洽詢。',
    confirmation:
      '看房時間、議價、購買條件、貸款與許可需另行確認。請透過專用聊天告知需求。目前尚未預約或送出聯絡訊息。',
    error: '暫時無法取得回答，請再試一次。',
    rate: '提問較頻繁，請稍候再試。',
    unavailable: '這間房產已停止公開，無法使用聊天。',
    propertyType: '房產類型',
    builtYear: '建築年份',
    structure: '構造',
    floorCount: '樓層數',
    price: '刊登售價',
    buildingArea: '建築面積',
    landArea: '土地面積',
    access: '車站交通',
    building: '建築年份與構造',
    location: '公開地址',
    status: '現況',
    year: '年',
    floors: '層',
    walk: '步行',
    minutes: '分鐘',
    suggestions: [
      '價格與面積是多少？',
      '最近車站步行幾分鐘？',
      '建築年份與構造是？',
      '想諮詢看房',
    ],
  },
  'zh-CN': {
    title: '房源信息自动回答',
    subtitle: '根据已公开的房产信息自动回答。',
    welcome: '可以咨询这套房产的价格、面积、车站距离或建筑信息。',
    placeholder: '例如：价格与建筑面积是多少？',
    send: '发送',
    clear: '清除对话',
    question: '关于这套房产的问题',
    working: '正在确认公开信息…',
    inquiry: '看房与详细咨询',
    source: '参考：这套房产的公开信息',
    privacy: '对话仅保留在本页。联系团队请使用专用聊天。',
    unknown: '公开信息未注明。',
    fallback:
      '公开信息无法确认这个问题。可以询问价格、面积、车站与建筑信息；其他问题请通过专用聊天确认。',
    restricted: '聊天不提供详细门牌或内部文件。所需信息请通过专用聊天咨询。',
    confirmation:
      '看房时间、议价、购买条件、贷款与许可需另行确认。请通过专用聊天告知需求。目前尚未预约或发送联系消息。',
    error: '暂时无法取得回答，请再试一次。',
    rate: '提问较频繁，请稍后再试。',
    unavailable: '这套房产已停止公开，无法使用聊天。',
    propertyType: '房产类型',
    builtYear: '建筑年份',
    structure: '结构',
    floorCount: '楼层数',
    price: '刊登售价',
    buildingArea: '建筑面积',
    landArea: '土地面积',
    access: '车站交通',
    building: '建筑年份与结构',
    location: '公开地址',
    status: '现状',
    year: '年',
    floors: '层',
    walk: '步行',
    minutes: '分钟',
    suggestions: [
      '价格与面积是多少？',
      '最近车站步行几分钟？',
      '建筑年份与结构是？',
      '想咨询看房',
    ],
  },
}

export function getListingChatCopy(locale: string) {
  return copies[locale as ChatLocale] || copies.en
}
