const copies = {
  ja: { with: 'で続ける', or: 'または', emailLink: 'メールのリンクで登録・ログイン', emailNote: 'パスワードを使わず、メールに届くリンクで進めます。同じメールの登録済みアカウントにも利用できます。', send: 'ログインリンクを送信', sent: 'メールをご確認ください。リンクを送信したブラウザで開いてください。迷惑メールも確認してください。', change: '別のメールアドレスを使う', failed: 'ログインできませんでした。もう一度お試しください。', emailFailed: 'メールを送信できませんでした。少し待ってからお試しください。', connecting: '接続しています…', notice: 'ログイン用にメールアドレスと基本プロフィールを利用します。各サービスのパスワードを自由不動産へ入力する必要はありません。', adminTitle: 'ログイン方法', active: '接続設定済み', required: '接続登録が必要', operatorNote: 'お客様のログインテストではなく、運営側で一度行うサービスとの接続登録です。設定が済んだ方法だけをお客様の画面に表示します。', setup: '設定手順を見る', console: '認証設定を開く', callback: 'サービス側に登録するコールバックURL', wechat: 'WeChat（微信）', wechatPending: '専用接続の確認が必要', wechatNote: '微信开放平台のサイトアプリ登録と利用条件を確認します。微信のIDを、メールの一致やニックネームだけで既存アカウントに結び付けません。', selected: "Google・Apple・Facebook・WeChat（微信）を導入対象にしています。", callbackNote: "Google・Apple・Facebookの接続で使用します。WeChatの接続先は専用実装を確認してから登録します。", requirements: {"google": "Google Cloudでログイン用アプリを登録し、接続情報を設定します。", "apple": "Apple Developerの登録、サイト用ID、署名キーが必要です。接続用の秘密キーは6か月以内に更新します。", "facebook": "Metaでログイン用アプリを登録し、一般のお客様が使える公開設定を確認します。"} },
  en: { with: 'Continue with', or: 'or', emailLink: 'Register or sign in with an email link', emailNote: 'Use a link sent to your email without a password. You can also use an existing account with the same email.', send: 'Send sign-in link', sent: 'Check your email and open the link in the browser that requested it. Please also check spam.', change: 'Use another email address', failed: 'Unable to sign in. Please try again.', emailFailed: 'Unable to send the email. Please wait a moment and try again.', connecting: 'Connecting…', notice: 'We use your email and basic profile for sign-in. You do not need to enter your provider password on Ziyou.', adminTitle: 'Sign-in methods', active: 'Connection configured', required: 'Provider setup required', operatorNote: 'This is one-time setup by the site operator, rather than a customer sign-in test. Only configured methods appear on the customer screen.', setup: 'View setup guide', console: 'Open authentication settings', callback: 'Callback URL to register with the provider', wechat: 'WeChat', wechatPending: 'Dedicated integration needs review', wechatNote: 'Confirm the website-app registration and conditions on WeChat Open Platform. Never link a WeChat ID to an existing account by matching an email or nickname alone.', selected: "Selected providers: Google, Apple, Facebook and WeChat.", callbackNote: "Used for Google, Apple and Facebook. Register the WeChat callback after its dedicated integration is verified.", requirements: {"google": "Register a sign-in app in Google Cloud and configure its connection.", "apple": "Requires Apple Developer registration, a website Services ID and a signing key. Rotate the client secret within six months.", "facebook": "Register a sign-in app with Meta and confirm it is ready for use by customers beyond app testers."} },
  'zh-TW': { with: '繼續', or: '或', emailLink: '以郵件連結註冊或登入', emailNote: '不需密碼，使用寄到信箱的連結。也可登入相同信箱的現有帳號。', send: '寄送登入連結', sent: '請查看郵件，並在申請連結的瀏覽器中開啟。也請確認垃圾郵件。', change: '使用其他電子郵件', failed: '無法登入，請重試。', emailFailed: '無法寄送郵件，請稍後再試。', connecting: '連線中…', notice: '登入使用您的電子郵件與基本個人資料，不需在自由不動產輸入各服務的密碼。', adminTitle: '登入方式', active: '已設定連線', required: '需要服務端設定', operatorNote: '這是網站營運方一次性的連線設定，不是請客戶測試登入。僅在客戶畫面顯示已設定的方式。', setup: '查看設定步驟', console: '開啟認證設定', callback: '在服務端登記的回呼網址', wechat: 'WeChat（微信）', wechatPending: '需要確認專用連線', wechatNote: '確認微信开放平台的網站應用註冊與使用條件。不會只依電子郵件或暱稱將微信ID連結至現有帳號。', selected: "導入對象為Google、Apple、Facebook與WeChat（微信）。", callbackNote: "供Google、Apple和Facebook連線使用。微信的回呼網址須在確認專用整合後登記。", requirements: {"google": "在Google Cloud註冊登入應用，並設定連線資訊。", "apple": "需要Apple Developer註冊、網站Services ID及簽署金鑰。連線密鑰須於六個月內更新。", "facebook": "在Meta註冊登入應用，並確認一般客戶可使用的公開設定。"} },
  'zh-CN': { with: '继续', or: '或', emailLink: '通过邮件链接注册或登录', emailNote: '无需密码，使用发送到邮箱的链接。也可登录相同邮箱的现有账号。', send: '发送登录链接', sent: '请查看邮件，并在申请链接的浏览器中打开。也请检查垃圾邮件。', change: '使用其他电子邮箱', failed: '无法登录，请重试。', emailFailed: '无法发送邮件，请稍后重试。', connecting: '连接中…', notice: '登录使用您的电子邮箱与基本个人资料，无需在自由不动产输入各服务的密码。', adminTitle: '登录方式', active: '已配置连接', required: '需要服务端配置', operatorNote: '这是网站运营方一次性的连接设置，不是请客户测试登录。仅在客户界面显示已配置的方式。', setup: '查看配置步骤', console: '打开认证设置', callback: '在服务端登记的回调网址', wechat: 'WeChat（微信）', wechatPending: '需要确认专用连接', wechatNote: '确认微信开放平台的网站应用注册与使用条件。不会只按电子邮箱或昵称将微信ID关联到现有账号。', selected: "接入目标为Google、Apple、Facebook和WeChat（微信）。", callbackNote: "供Google、Apple和Facebook连接使用。微信的回调网址须在确认专用集成后登记。", requirements: {"google": "在Google Cloud注册登录应用，并配置连接信息。", "apple": "需要Apple Developer注册、网站Services ID及签名密钥。连接密钥须在六个月内更新。", "facebook": "在Meta注册登录应用，并确认普通客户可使用的公开配置。"} },
} as const

export function getLoginMethodsCopy(locale: string) { return copies[locale as keyof typeof copies] || copies.en }
export function socialButtonLabel(name: string, locale: string) {
  const copy = getLoginMethodsCopy(locale)
  return locale === 'en' ? `${copy.with} ${name}` : locale === 'ja' ? `${name}${copy.with}` : `使用 ${name} ${copy.with}`
}
