const copy = {
  ja: {
    details: '物件種別・エリア・キーワード',
    intro: '場所と予算から、東京の売買物件を絞り込む。',
    location: '駅・区・路線から探す',
    locationPlaceholder: '例：森下、新宿区、山手線',
    noLocations: '一致する場所がありません',
    ward: 'エリア',
    line: '路線',
    station: '駅',
    price: '購入価格',
    priceUnit: '万円',
    size: '面積',
    sizeNote: '土地は土地面積、それ以外は建物面積で検索します。',
    minimum: '下限',
    maximum: '上限',
    apply: '範囲を適用',
    invalidRange: '下限は上限以下にしてください。',
    distribution: '公開物件の売出価格の分布',
    areaDistribution: '公開物件の面積の分布',
    pickRange: '棒を押すとその範囲で絞り込みます',
    allListings: '公開物件',
    matches: '条件に一致',
    criteria: '選択中の条件',
    remove: '解除',
    save: 'この条件を保存',
    saved: '保存した条件',
    savedNotice: '検索条件を保存しました。',
    browserOnly: 'このブラウザーに保存されます。',
    deleteSaved: '保存条件を削除',
    storageError: 'このブラウザーでは条件を保存できません。',
    allCriteria: 'すべての条件',
    searching: '検索中',
    results: '件',
    range: '表示',
    sort: '並び順',
    keyword: 'キーワード',
    clear: 'すべて解除',
    unknown: '未確認',
    walk: '駅徒歩',
    minutes: '分以内',
    purpose: '購入目的',
    type: '物件種別',
    from: '以上',
    to: '以下',
    savedEmpty: '気になる条件を保存して、次回の検索に使えます。',
  },
  en: {
    details: 'Type, area and keyword',
    intro: 'Narrow your Tokyo property search by location and budget.',
    location: 'Find a station, area or train line',
    locationPlaceholder: 'e.g. Morishita, Shinjuku, Yamanote',
    noLocations: 'No matching locations',
    ward: 'Area',
    line: 'Train line',
    station: 'Station',
    price: 'Purchase price',
    priceUnit: 'JPY million',
    size: 'Area',
    sizeNote:
      'Land area for land listings; building area for other properties.',
    minimum: 'Minimum',
    maximum: 'Maximum',
    apply: 'Apply range',
    invalidRange: 'The minimum must not exceed the maximum.',
    distribution: 'Asking-price distribution of published listings',
    areaDistribution: 'Floor-area distribution of published listings',
    pickRange: 'Tap a bar to filter to that range',
    allListings: 'Published',
    matches: 'Matching',
    criteria: 'Selected filters',
    remove: 'Remove',
    save: 'Save this search',
    saved: 'Saved searches',
    savedNotice: 'Search criteria saved.',
    browserOnly: 'Saved in this browser.',
    deleteSaved: 'Delete saved search',
    storageError: 'This browser cannot save search criteria.',
    allCriteria: 'All criteria',
    searching: 'Searching',
    results: 'properties',
    range: 'Showing',
    sort: 'Sort',
    keyword: 'Keyword',
    clear: 'Clear all',
    unknown: 'Unconfirmed',
    walk: 'Station walk',
    minutes: 'min or less',
    purpose: 'Purpose',
    type: 'Property type',
    from: 'or more',
    to: 'or less',
    savedEmpty: 'Save a useful set of criteria for your next search.',
  },
  'zh-TW': {
    details: '物件類型、區域與關鍵字',
    intro: '依地點與預算，篩選東京待售物件。',
    location: '搜尋車站、區域或路線',
    locationPlaceholder: '例如：森下、新宿區、山手線',
    noLocations: '找不到符合的地點',
    ward: '區域',
    line: '路線',
    station: '車站',
    price: '購買價格',
    priceUnit: '萬日圓',
    size: '面積',
    sizeNote: '土地依土地面積，其他物件依建物面積搜尋。',
    minimum: '最低',
    maximum: '最高',
    apply: '套用範圍',
    invalidRange: '最低值不能高於最高值。',
    distribution: '公開物件的開價分布',
    areaDistribution: '公開物件的面積分布',
    pickRange: '點選長條即可篩選該範圍',
    allListings: '公開物件',
    matches: '符合條件',
    criteria: '已選條件',
    remove: '移除',
    save: '儲存這組條件',
    saved: '已儲存條件',
    savedNotice: '已儲存搜尋條件。',
    browserOnly: '儲存在此瀏覽器。',
    deleteSaved: '刪除已儲存條件',
    storageError: '此瀏覽器無法儲存搜尋條件。',
    allCriteria: '所有條件',
    searching: '搜尋中',
    results: '件',
    range: '顯示',
    sort: '排序',
    keyword: '關鍵字',
    clear: '全部清除',
    unknown: '未確認',
    walk: '車站步行',
    minutes: '分鐘以內',
    purpose: '購買目的',
    type: '物件類型',
    from: '以上',
    to: '以下',
    savedEmpty: '儲存常用條件，方便下次搜尋。',
  },
  'zh-CN': {
    details: '房产类型、区域与关键词',
    intro: '按位置与预算，筛选东京待售房产。',
    location: '搜索车站、区域或线路',
    locationPlaceholder: '例如：森下、新宿区、山手线',
    noLocations: '没有匹配的位置',
    ward: '区域',
    line: '线路',
    station: '车站',
    price: '购买价格',
    priceUnit: '万日元',
    size: '面积',
    sizeNote: '土地按土地面积，其他房产按建筑面积搜索。',
    minimum: '最低',
    maximum: '最高',
    apply: '应用范围',
    invalidRange: '最低值不能高于最高值。',
    distribution: '公开房源的挂牌价格分布',
    areaDistribution: '公开房源的面积分布',
    pickRange: '点击柱状条即可筛选该范围',
    allListings: '公开房源',
    matches: '符合条件',
    criteria: '已选条件',
    remove: '移除',
    save: '保存这组条件',
    saved: '已保存条件',
    savedNotice: '已保存搜索条件。',
    browserOnly: '保存在此浏览器。',
    deleteSaved: '删除已保存条件',
    storageError: '此浏览器无法保存搜索条件。',
    allCriteria: '所有条件',
    searching: '搜索中',
    results: '套',
    range: '显示',
    sort: '排序',
    keyword: '关键词',
    clear: '全部清除',
    unknown: '未确认',
    walk: '车站步行',
    minutes: '分钟以内',
    purpose: '购买目的',
    type: '房产类型',
    from: '以上',
    to: '以下',
    savedEmpty: '保存常用条件，方便下次搜索。',
  },
} as const

export function getSearchExperienceCopy(locale: string) {
  return copy[locale as keyof typeof copy] || copy.en
}

export function formatSearchPrice(value: number, locale: string) {
  if (locale === 'en')
    return `¥${(value / 1_000_000).toLocaleString('en', { maximumFractionDigits: 2 })}M`
  return `¥${(value / 10_000).toLocaleString('ja-JP', { maximumFractionDigits: 0 })}${locale === 'zh-TW' ? '萬' : '万'}`
}

/** Short axis labels: 2,000万 / 1.5億 in Japanese and Chinese, ¥20M in English. */
export function formatCompactPrice(value: number, locale: string): string {
  if (locale === 'en') return `¥${(value / 1_000_000).toLocaleString('en', { maximumFractionDigits: 1 })}M`
  const tenThousand = locale === 'zh-TW' ? '萬' : '万'
  const hundredMillion = locale === 'zh-TW' ? '億' : locale === 'zh-CN' ? '亿' : '億'
  return value >= 100_000_000
    ? `${(value / 100_000_000).toLocaleString('ja-JP', { maximumFractionDigits: 1 })}${hundredMillion}`
    : `${(value / 10_000).toLocaleString('ja-JP', { maximumFractionDigits: 0 })}${tenThousand}`
}
