import type { GuideArticle } from './guides'

/** Glossary of terms used in Japanese property listings, for international buyers. */
export const extraGuideArticles4: GuideArticle[] = [
  {
    slug: 'japanese-property-listing-terms',
    publishedAt: '2026-10-07',
    updatedAt: '2026-10-07',
    readMinutes: 7,
    tags: ['glossary', 'foreign buyer', 'listing terms'],
    locales: {
      ja: {
        category: '用語集',
        title: '日本の物件情報の用語集｜LDK・坪・壁芯・オーナーチェンジなど',
        excerpt: '間取りの「LDK」、面積の「壁芯」と「内法」、「オーナーチェンジ」や「再建築不可」など、物件情報によく出る言葉を、海外の方にも伝わるように整理しました。',
        seoDescription: '日本の不動産物件情報の用語集。1LDKなど間取り、坪と㎡、壁芯と内法、管理費・修繕積立金、新耐震、所有権と借地権、オーナーチェンジ、表面利回りと実質利回りを解説。',
        intro: '日本の物件情報には、独特の略語や専門用語が多く出てきます。当サイトの物件ページに出てくる言葉を中心に、意味と確認のポイントをまとめました。',
        keyTakeaways: [
          '「2LDK」は、居室2つと、リビング・ダイニング・キッチンが一体の部屋',
          '1坪は約3.31㎡。マンションの面積は壁芯と内法で数字が違う',
          '「オーナーチェンジ」は、入居者がいる状態で売買される物件',
          '利回りは表面と実質の2種類。実質は費用を差し引いた数字',
        ],
        sections: [
          {
            id: 'layout',
            heading: '間取りと広さ',
            paragraphs: ['間取りは「部屋の数＋記号」で表します。'],
            bullets: [
              'R（ワンルーム）：キッチンと居室が同じ空間',
              'K・DK・LDK：キッチン、ダイニングキッチン、リビング・ダイニング・キッチン。数字は居室の数（例：2LDK＝居室2つ＋LDK）',
              'S（サービスルーム）：窓が小さいなどで居室と表示できない部屋。納戸とも呼ぶ',
              '坪：約3.31㎡。土地の価格は「坪単価」で語られることが多い',
              '壁芯面積と内法面積：壁の中心で測るか、内側で測るか。登記簿の面積は内法で、壁芯より小さくなる',
            ],
          },
          {
            id: 'costs',
            heading: 'お金に関する言葉',
            paragraphs: [],
            bullets: [
              '仲介手数料：不動産会社に払う手数料。上限は「価格×3%＋6万円＋消費税」',
              '管理費・修繕積立金：マンションで毎月払う費用。日常の管理と将来の大規模修繕のため',
              '手付金：契約時に払う代金の一部（物件価格の5〜10%程度が多い）',
              '固定資産税・都市計画税：毎年1月1日の所有者にかかる税金。売買時は日割りで精算',
              '㎡単価：価格を面積で割った数字。物件同士を比べるときの目安',
            ],
          },
          {
            id: 'building',
            heading: '建物に関する言葉',
            paragraphs: [],
            bullets: [
              '新耐震・旧耐震：1981年6月以降の建築確認なら新耐震基準',
              'RC・SRC・S・木造：鉄筋コンクリート造、鉄骨鉄筋コンクリート造、鉄骨造、木造',
              '築年：建物が完成した年。「築30年」は完成から30年',
              '区分マンション：マンションの1室を所有する形。一棟マンション・一棟ビルは建物全体',
              '大規模修繕：外壁・屋上防水・配管などを10数年ごとにまとめて直す工事',
            ],
          },
          {
            id: 'legal',
            heading: '権利と法律に関する言葉',
            paragraphs: [],
            bullets: [
              '所有権・借地権：土地も所有するか、土地を借りるか',
              '用途地域：建てられる建物の種類や高さを決める区分（第一種低層住居専用地域、商業地域など）',
              '再建築不可：道路の条件などにより、今の建物を壊すと建て直せない土地',
              '重要事項説明：契約前に宅地建物取引士が物件の権利や法令の制限を説明する手続き',
              '登記：所有者を法務局の記録に載せる手続き。司法書士が代行する',
            ],
          },
          {
            id: 'rental',
            heading: '賃貸・投資に関する言葉',
            paragraphs: [],
            bullets: [
              '現況：今の状態。「空室」「居住中」「賃貸中」など',
              'オーナーチェンジ：入居者がいる状態で売買し、賃貸契約を引き継ぐ物件',
              'サブリース：管理会社が部屋を借り上げて転貸する契約',
              '表面利回り：年間賃料÷物件価格。費用を引く前の数字',
              '実質利回り：管理費・修繕積立金などを差し引いた年間の手取り÷物件価格',
            ],
          },
        ],
        faq: [
          { question: '「徒歩10分」はどう測っていますか？', answer: '道路距離80mを1分として計算するルールです。信号や坂は考慮されないため、実際にはもう少しかかることがあります。' },
          { question: '面積が物件ページと登記簿で違うのはなぜですか？', answer: '物件ページは壁芯、登記簿は内法で測ることが多いためです。どちらの面積かは物件情報に記載しています。' },
          { question: 'わからない言葉があったら？', answer: '物件ページの自動回答や、WhatsApp・メールでお気軽にお尋ねください。' },
        ],
        ctaTitle: '物件ページで実際に見てみる',
        ctaDescription: '用語を確認しながら、公開中の物件の情報を見比べてみましょう。',
      },
      en: {
        category: 'Glossary',
        title: 'Japanese Property Listing Terms Explained: LDK, Tsubo, Owner-Change and More',
        excerpt: 'What 2LDK means, tsubo and square metres, wall-centre vs internal area, owner-change units, "cannot be rebuilt", and gross vs net yield, explained for international buyers.',
        seoDescription: 'Glossary of Japanese real estate listing terms for foreigners: 1LDK and 2LDK, tsubo, wall-centre vs internal floor area, management fees, earthquake standards, leasehold, owner-change and yields.',
        intro: 'Japanese property listings use many abbreviations and technical terms. This glossary covers the words you will see on our listing pages, with what each one means and what to check.',
        keyTakeaways: [
          '2LDK means two rooms plus a combined living, dining and kitchen area',
          'One tsubo is about 3.31 m²; condo areas differ between wall-centre and internal measurements',
          'An owner-change property is sold with a tenant in place',
          'Gross yield is before costs; net yield is after them',
        ],
        sections: [
          {
            id: 'layout',
            heading: 'Layout and size',
            paragraphs: ['Layouts are written as a number of rooms plus letters.'],
            bullets: [
              'R (one-room): the kitchen and the room are one space',
              'K, DK, LDK: kitchen, dining-kitchen, living-dining-kitchen. The number counts the other rooms (2LDK = two rooms + LDK)',
              'S (service room): a room that cannot legally be called a living room, often because of small windows; also called a storage room',
              'Tsubo: about 3.31 m². Land prices are often quoted per tsubo',
              'Wall-centre vs internal area: measured to the middle of the walls or to their inside. The registered area is internal and smaller',
            ],
          },
          {
            id: 'costs',
            heading: 'Money terms',
            paragraphs: [],
            bullets: [
              'Brokerage fee: paid to the agent; the maximum is price × 3% + ¥60,000 + consumption tax',
              'Management fee and repair reserve: monthly condo fees for running costs and future major repairs',
              'Deposit (tetsukekin): part of the price paid at the contract, often 5–10%',
              'Fixed asset and city planning tax: charged yearly to the owner on 1 January and split pro rata in a sale',
              'Price per m²: price divided by area, useful for comparing properties',
            ],
          },
          {
            id: 'building',
            heading: 'Building terms',
            paragraphs: [],
            bullets: [
              'New vs old earthquake standard: buildings permitted from June 1981 follow the new standard',
              'RC, SRC, S, wooden: reinforced concrete, steel-reinforced concrete, steel frame, timber',
              'Built year (chiku): the year of completion; "chiku 30" means 30 years old',
              'Condominium unit (kubun): owning one unit in a building; a whole building is sold as an apartment or commercial building',
              'Major repairs: exterior, roof and pipe works done together every 10–15 years or so',
            ],
          },
          {
            id: 'legal',
            heading: 'Rights and legal terms',
            paragraphs: [],
            bullets: [
              'Freehold vs leasehold: owning the land or leasing it',
              'Zoning: the district rules on what can be built and how tall, such as Category I Exclusively Low-rise Residential or Commercial',
              'Cannot be rebuilt (saikenchiku fuka): land where a new building is not allowed if the current one is demolished, usually because of road access',
              'Important matters explanation: the formal disclosure by a licensed agent before the contract',
              'Registration: recording the owner at the Legal Affairs Bureau, handled by a judicial scrivener',
            ],
          },
          {
            id: 'rental',
            heading: 'Rental and investment terms',
            paragraphs: [],
            bullets: [
              'Current status: vacant, owner-occupied or let',
              'Owner-change: sold with a tenant in place; the buyer takes over the lease',
              'Sublease (master lease): a company rents the unit and sublets it',
              'Gross yield: annual rent ÷ price, before costs',
              'Net yield: annual rent minus building fees and other costs, ÷ price',
            ],
          },
        ],
        faq: [
          { question: 'How is "10 minutes\' walk" measured?', answer: 'By rule, every 80 m of road counts as one minute. Traffic lights and hills are ignored, so it can take a little longer.' },
          { question: 'Why does the area differ from the registered area?', answer: 'Listings often use the wall-centre area and the register uses the internal area. We state which one a listing uses.' },
          { question: 'What if I see a term I do not know?', answer: 'Ask the property facts assistant on the listing page, or message us by WhatsApp or email.' },
        ],
        ctaTitle: 'See the terms on real listings',
        ctaDescription: 'Compare current listings with this glossary at hand.',
      },
      'zh-TW': {
        category: '用語集',
        title: '日本物件資訊用語集｜LDK、坪、壁芯、帶租約（オーナーチェンジ）等',
        excerpt: '整理日本物件資訊常見用語：格局「LDK」、面積的「壁芯」與「內法」、「帶租約」、「不可重建」等，讓海外買家也能看懂。',
        seoDescription: '日本不動產物件資訊用語集：1LDK等格局、坪與平方公尺、壁芯與內法面積、管理費與修繕公積金、新耐震、所有權與借地權、帶租約、表面與實質投報率。',
        intro: '日本的物件資訊有很多獨特的縮寫與專業用語。以下以本站物件頁面會出現的用語為主，整理意思與確認重點。',
        keyTakeaways: [
          '「2LDK」是2個房間加上客廳、餐廳、廚房合一的空間',
          '1坪約3.31平方公尺；公寓面積有壁芯與內法兩種量法',
          '「帶租約（オーナーチェンジ）」是有租客居住中出售的物件',
          '投報率分為表面與實質，實質是扣除費用後的數字',
        ],
        sections: [
          {
            id: 'layout',
            heading: '格局與面積',
            paragraphs: ['格局以「房間數＋代號」表示。'],
            bullets: [
              'R（套房）：廚房與房間為同一空間',
              'K・DK・LDK：廚房、餐廚、客餐廚。數字為房間數（例：2LDK＝2房＋LDK）',
              'S（服務間）：因採光等條件不能標示為居室的房間，也稱儲藏室',
              '坪：約3.31平方公尺，土地價格常以「坪單價」表示',
              '壁芯與內法面積：量到牆壁中心或內側。登記面積為內法，比壁芯小',
            ],
          },
          {
            id: 'costs',
            heading: '金錢相關用語',
            paragraphs: [],
            bullets: [
              '仲介費：付給不動產公司的手續費，上限為「價格×3%＋6萬日圓＋消費稅」',
              '管理費・修繕公積金：公寓每月費用，用於日常管理與未來大規模修繕',
              '訂金：簽約時支付的部分價款（多為物件價格的5〜10%）',
              '固定資產稅・都市計畫稅：每年向1月1日的所有人課徵，買賣時按日分攤',
              '每平方公尺單價：價格除以面積，比較物件時的參考',
            ],
          },
          {
            id: 'building',
            heading: '建物相關用語',
            paragraphs: [],
            bullets: [
              '新耐震・舊耐震：1981年6月以後取得建築許可者為新耐震基準',
              'RC・SRC・S・木造：鋼筋混凝土、鋼骨鋼筋混凝土、鋼骨、木造',
              '屋齡：建物完工後的年數',
              '區分公寓：擁有公寓中的一戶；整棟公寓・整棟大樓則為整棟建物',
              '大規模修繕：外牆、屋頂防水、管線等每十幾年集中進行的工程',
            ],
          },
          {
            id: 'legal',
            heading: '權利與法律用語',
            paragraphs: [],
            bullets: [
              '所有權・借地權：連土地一起擁有，或租用土地',
              '用途地域：規定可建建物種類與高度的分區（第一種低層住居專用地域、商業地域等）',
              '不可重建：因道路條件等，拆除現有建物後無法重建的土地',
              '重要事項說明：簽約前由宅地建物交易士說明權利與法規限制的手續',
              '登記：將所有人記錄於法務局，由司法書士代辦',
            ],
          },
          {
            id: 'rental',
            heading: '租賃與投資用語',
            paragraphs: [],
            bullets: [
              '現況：目前狀態，如「空屋」「自住中」「出租中」',
              '帶租約（オーナーチェンジ）：有租客居住中出售並承接租約的物件',
              '包租（サブリース）：管理公司承租後轉租的契約',
              '表面投報率：年租金÷物件價格，扣除費用前的數字',
              '實質投報率：扣除管理費・修繕公積金等後的年收入÷物件價格',
            ],
          },
        ],
        faq: [
          { question: '「步行10分鐘」怎麼計算？', answer: '依規定以道路距離80公尺為1分鐘計算，不考慮紅綠燈與坡道，實際可能稍久。' },
          { question: '為什麼面積與登記簿不同？', answer: '物件資訊多用壁芯面積，登記簿用內法面積。物件資訊會註明是哪一種。' },
          { question: '遇到看不懂的用語怎麼辦？', answer: '可使用物件頁面的自動回答，或透過WhatsApp、電子郵件詢問。' },
        ],
        ctaTitle: '在物件頁面實際看看',
        ctaDescription: '對照用語集，比較目前刊登中的物件資訊。',
      },
      'zh-CN': {
        category: '用语集',
        title: '日本房源信息用语集｜LDK、坪、壁芯、带租约（オーナーチェンジ）等',
        excerpt: '整理日本房源信息常见用语：户型“LDK”、面积的“壁芯”与“内法”、“带租约”、“不可重建”等，让海外买家也能看懂。',
        seoDescription: '日本房产房源信息用语集：1LDK等户型、坪与平方米、壁芯与内法面积、管理费与修缮基金、新耐震、所有权与借地权、带租约、表面与实际收益率。',
        intro: '日本的房源信息有很多独特的缩写与专业用语。以下以本站房源页面会出现的用语为主，整理含义与确认要点。',
        keyTakeaways: [
          '“2LDK”是2个房间加上客厅、餐厅、厨房合一的空间',
          '1坪约3.31平方米；公寓面积有壁芯与内法两种量法',
          '“带租约（オーナーチェンジ）”是有租客居住中出售的房源',
          '收益率分为表面与实际，实际是扣除费用后的数字',
        ],
        sections: [
          {
            id: 'layout',
            heading: '户型与面积',
            paragraphs: ['户型以“房间数＋代号”表示。'],
            bullets: [
              'R（单间）：厨房与房间为同一空间',
              'K・DK・LDK：厨房、餐厨、客餐厨。数字为房间数（例：2LDK＝2房＋LDK）',
              'S（服务间）：因采光等条件不能标示为居室的房间，也称储物间',
              '坪：约3.31平方米，土地价格常以“坪单价”表示',
              '壁芯与内法面积：量到墙壁中心或内侧。登记面积为内法，比壁芯小',
            ],
          },
          {
            id: 'costs',
            heading: '金钱相关用语',
            paragraphs: [],
            bullets: [
              '中介费：付给房产公司的手续费，上限为“价格×3%＋6万日元＋消费税”',
              '管理费・修缮基金：公寓每月费用，用于日常管理与未来大规模修缮',
              '定金：签约时支付的部分房款（多为房价的5〜10%）',
              '固定资产税・城市规划税：每年向1月1日的业主征收，买卖时按日分摊',
              '每平方米单价：价格除以面积，比较房源时的参考',
            ],
          },
          {
            id: 'building',
            heading: '建筑相关用语',
            paragraphs: [],
            bullets: [
              '新耐震・旧耐震：1981年6月以后取得建筑许可者为新耐震标准',
              'RC・SRC・S・木造：钢筋混凝土、钢骨钢筋混凝土、钢结构、木结构',
              '房龄：建筑竣工后的年数',
              '区分公寓：拥有公寓中的一户；整栋公寓・整栋大楼则为整栋建筑',
              '大规模修缮：外墙、屋顶防水、管道等每十几年集中进行的工程',
            ],
          },
          {
            id: 'legal',
            heading: '权利与法律用语',
            paragraphs: [],
            bullets: [
              '所有权・借地权：连土地一起拥有，或租用土地',
              '用途地域：规定可建建筑种类与高度的分区（第一种低层住居专用地域、商业地域等）',
              '不可重建：因道路条件等，拆除现有建筑后无法重建的土地',
              '重要事项说明：签约前由宅地建物交易士说明权利与法规限制的手续',
              '登记：将业主记录于法务局，由司法书士代办',
            ],
          },
          {
            id: 'rental',
            heading: '租赁与投资用语',
            paragraphs: [],
            bullets: [
              '现况：目前状态，如“空置”“自住中”“出租中”',
              '带租约（オーナーチェンジ）：有租客居住中出售并承接租约的房源',
              '包租（サブリース）：管理公司承租后转租的合同',
              '表面收益率：年租金÷房价，扣除费用前的数字',
              '实际收益率：扣除管理费・修缮基金等后的年收入÷房价',
            ],
          },
        ],
        faq: [
          { question: '“步行10分钟”怎么计算？', answer: '按规定以道路距离80米为1分钟计算，不考虑红绿灯与坡道，实际可能稍久。' },
          { question: '为什么面积与登记簿不同？', answer: '房源信息多用壁芯面积，登记簿用内法面积。房源信息会注明是哪一种。' },
          { question: '遇到看不懂的用语怎么办？', answer: '可以使用房源页面的自动回答，或通过WhatsApp、电子邮件咨询。' },
        ],
        ctaTitle: '在房源页面实际看看',
        ctaDescription: '对照用语集，比较当前在售的房源信息。',
      },
    },
  },
]
