export type HelpLocale = 'ja' | 'en' | 'zh-TW' | 'zh-CN'
type Text = { title: string; body: string; action: string }
export type HelpArticle = {
  id: string
  category: 'search' | 'listing' | 'account'
  href: string
  keywords: string[]
  text: Record<HelpLocale, Text>
}

/** Public product instructions only. This content is also the answer source. */
export const helpArticles: HelpArticle[] = [
  {
    id: 'search',
    category: 'search',
    href: '/listings',
    keywords: [
      '検索',
      '探し',
      '価格帯',
      '面積',
      '駅',
      '沿線',
      '路線',
      '徒歩',
      'エリア',
      '区',
      '条件',
      'search',
      'filter',
      'station',
      'train line',
      'railway line',
      'area',
      'walk',
      'size',
      '搜尋',
      '搜索',
      '篩選',
      '筛选',
      '车站',
      '車站',
      '路線',
      '线路',
      '步行',
      '面积',
      '面積',
    ],
    text: {
      ja: {
        title: '条件に合う物件を探すには？',
        body: '物件一覧で、用途・物件種別・価格・面積・エリア・駅・徒歩分数を指定できます。スマートフォンでは絞り込みボタンから条件を開きます。結果が少ない場合は、選択中の条件を外すか、価格やエリアを広げてください。',
        action: '物件を検索する',
      },
      en: {
        title: 'How do I find a property?',
        body: 'Use the listings page to filter by purpose, property type, price, size, area, station and walking time. On mobile, open the filters button. If there are few results, remove selected filters or widen the price or location range.',
        action: 'Search properties',
      },
      'zh-TW': {
        title: '如何搜尋符合條件的物件？',
        body: '在物件列表設定用途、物件類型、價格、面積、區域、車站及步行時間。手機版請打開篩選按鈕。結果較少時，可以移除已選條件，或放寬價格及區域。',
        action: '搜尋物件',
      },
      'zh-CN': {
        title: '如何搜索符合条件的房产？',
        body: '在房产列表设置用途、房产类型、价格、面积、区域、车站及步行时间。手机版请打开筛选按钮。结果较少时，可以移除已选条件，或放宽价格及区域。',
        action: '搜索房产',
      },
    },
  },
  {
    id: 'saved-searches',
    category: 'search',
    href: '/listings',
    keywords: [
      '保存した検索',
      '条件保存',
      '条件を保存',
      '保存した条件',
      '通知',
      'saved search',
      'save a search',
      'save this search',
      'save my search',
      'save the search',
      'save search',
      'save filters',
      'alert',
      'notification',
      '儲存搜尋',
      '保存搜索',
      '儲存條件',
      '保存条件',
      '通知',
    ],
    text: {
      ja: {
        title: '検索条件の保存と、お気に入りの違いは？',
        body: '物件一覧の「検索条件を保存」は、そのブラウザーに条件を最大8件保存します。ログインは不要です。別の端末には同期されず、ブラウザーの保存データを消すと失われます。新着通知はありません。物件自体を保存するには、ログインして物件ページの「お気に入りに追加」を使ってください。',
        action: '検索条件を保存する',
      },
      en: {
        title: 'What are saved searches?',
        body: 'Save search on the listings page stores up to eight sets of filters in this browser, without signing in. They do not sync to another device and are lost if browser storage is cleared. There are no new-listing alerts. To save an individual property, sign in and use Add to favorites on its page.',
        action: 'Save search filters',
      },
      'zh-TW': {
        title: '儲存搜尋條件與收藏有何不同？',
        body: '物件列表的「儲存搜尋」可在目前瀏覽器保存最多8組條件，不必登入。不會同步到其他裝置，清除瀏覽器儲存資料後會消失。目前沒有新物件通知。若要收藏單一物件，請登入後在物件頁加入收藏。',
        action: '儲存搜尋條件',
      },
      'zh-CN': {
        title: '保存搜索条件与收藏有何不同？',
        body: '房产列表的“保存搜索”可在当前浏览器保存最多8组条件，不必登录。不会同步到其他设备，清除浏览器存储数据后会消失。目前没有新房源通知。若要收藏单个房产，请登录后在房产页加入收藏。',
        action: '保存搜索条件',
      },
    },
  },
  {
    id: 'favorites',
    category: 'account',
    href: '/favorites',
    keywords: [
      'お気に入り',
      'ブックマーク',
      'favorite',
      'favourite',
      'bookmark',
      '收藏',
    ],
    text: {
      ja: {
        title: '物件をお気に入りに追加するには？',
        body: 'ログインして物件ページの「お気に入りに追加」を押すと保存できます。保存済みの物件は、お気に入りページから開けます。掲載が終了した物件や公開対象外の物件は表示されません。',
        action: 'お気に入りを開く',
      },
      en: {
        title: 'How do I save a favorite property?',
        body: 'Sign in and select Add to favorites on the property page. Open the favorites page to revisit saved properties. Listings that are no longer published or eligible for public display will not appear.',
        action: 'Open favorites',
      },
      'zh-TW': {
        title: '如何收藏物件？',
        body: '登入後在物件頁按「加入收藏」即可儲存。已收藏的物件可從收藏頁查看。已停止刊登或不再公開的物件不會顯示。',
        action: '開啟收藏',
      },
      'zh-CN': {
        title: '如何收藏房产？',
        body: '登录后在房产页按“加入收藏”即可保存。已收藏的房产可从收藏页查看。已停止刊登或不再公开的房产不会显示。',
        action: '打开收藏',
      },
    },
  },
  {
    id: 'inquiries',
    category: 'listing',
    href: '/listings',
    keywords: [
      '問い合わせ',
      '問合せ',
      '内見',
      '見学',
      '相談',
      '予約',
      '連絡',
      'inquiry',
      'enquiry',
      'contact',
      'viewing',
      'book',
      'visit',
      'whatsapp',
      'wechat',
      'line id',
      'lineで',
      'line contact',
      'email',
      '詢問',
      '咨询',
      '諮詢',
      '聯絡',
      '联系',
      '看房',
      '预约',
      '預約',
    ],
    text: {
      ja: {
        title: '内見・詳細確認の問い合わせをするには？',
        body: 'ログイン後、対象の物件ページの問い合わせフォームで連絡方法、連絡先、相談内容を入力して送信してください。メール、LINE、WhatsApp、WeChatを選べます。自動回答を読むだけでは問い合わせは送信されず、内見予約も確定しません。',
        action: '問い合わせる物件を選ぶ',
      },
      en: {
        title: 'How do I ask about a property or viewing?',
        body: 'Sign in, then submit the inquiry form on the relevant property page with your contact method, contact details and message. You can choose email, LINE, WhatsApp or WeChat. Reading an automatic answer does not submit an inquiry or confirm a viewing.',
        action: 'Choose a property to ask about',
      },
      'zh-TW': {
        title: '如何詢問物件詳情或預約看房？',
        body: '登入後，在該物件頁的詢問表單填寫聯絡方式、聯絡資料及詢問內容，再提交。可選擇電子郵件、LINE、WhatsApp或WeChat。閱讀自動回答不會提交詢問，也不會確認看房預約。',
        action: '選擇要詢問的物件',
      },
      'zh-CN': {
        title: '如何咨询房产详情或预约看房？',
        body: '登录后，在该房产页的咨询表单填写联系方式、联系信息及咨询内容，再提交。可选择电子邮件、LINE、WhatsApp或WeChat。阅读自动回答不会提交咨询，也不会确认看房预约。',
        action: '选择要咨询的房产',
      },
    },
  },
  {
    id: 'property-chat',
    category: 'listing',
    href: '/listings',
    keywords: [
      'チャット',
      '自動回答',
      'ai',
      'chat',
      'bot',
      'automatic answer',
      '聊天',
      '自動回答',
      '自动回答',
      '智能',
    ],
    text: {
      ja: {
        title: '物件チャットは何を回答できますか？',
        body: '物件ページのチャットは、その物件の公開済みの価格、面積、駅、建物概要などを自動回答します。ログインは不要です。現在は公開情報に基づく定型回答です。担当者とのリアルタイム会話ではありません。不明な内容や内見の希望は、問い合わせフォームでご相談ください。',
        action: '物件チャットを使う',
      },
      en: {
        title: 'What can property chat answer?',
        body: 'Chat on a property page automatically answers from that property’s published price, size, stations and building facts, without signing in. It currently uses predefined answers based on public information. It is not a live conversation with staff. Use the inquiry form for unknown details or viewing requests.',
        action: 'Open a property chat',
      },
      'zh-TW': {
        title: '物件聊天可以回答什麼？',
        body: '物件頁的聊天功能會根據該物件已公開的價格、面積、車站及建築資料自動回答，不必登入。目前使用公開資料的固定回答，並非與工作人員即時對話。不明詳情或看房需求請透過詢問表單提出。',
        action: '使用物件聊天',
      },
      'zh-CN': {
        title: '房产聊天可以回答什么？',
        body: '房产页的聊天功能会根据该房产已公开的价格、面积、车站及建筑资料自动回答，不必登录。目前使用公开资料的固定回答，并非与工作人员实时对话。不明详情或看房需求请通过咨询表单提出。',
        action: '使用房产聊天',
      },
    },
  },
  {
    id: 'languages',
    category: 'account',
    href: '/listings',
    keywords: [
      '言語',
      '英語',
      '中国語',
      '日本語',
      'language',
      'english',
      'chinese',
      'japanese',
      'translate',
      '翻訳',
      '翻譯',
      '翻译',
      '語言',
      '语言',
      '中文',
      '日语',
      '日語',
    ],
    text: {
      ja: {
        title: '表示言語を変更するには？',
        body: '画面上部の言語メニューから、日本語、English、繁體中文、简体中文を選べます。ヘルプと自動回答も選択した言語で表示します。',
        action: '物件一覧へ',
      },
      en: {
        title: 'How do I change the language?',
        body: 'Use the language menu at the top of the page to select Japanese, English, Traditional Chinese or Simplified Chinese. Help and automatic answers use your selected language.',
        action: 'Browse listings',
      },
      'zh-TW': {
        title: '如何切換語言？',
        body: '透過頁面上方的語言選單，可選擇日本語、English、繁體中文及简体中文。幫助與自動回答也會使用所選語言。',
        action: '前往物件列表',
      },
      'zh-CN': {
        title: '如何切换语言？',
        body: '通过页面上方的语言菜单，可选择日本語、English、繁體中文及简体中文。帮助与自动回答也会使用所选语言。',
        action: '前往房产列表',
      },
    },
  },
  {
    id: 'public-information',
    category: 'listing',
    href: '/listings',
    keywords: [
      '非公開',
      '住所',
      '番地',
      'レインズ',
      'reins',
      'private',
      'address',
      'unpublished',
      'permission',
      '非公开',
      '非公開',
      '地址',
      '授权',
      '授權',
    ],
    text: {
      ja: {
        title: '住所の詳細や非公開物件も見られますか？',
        body: '広告許可を確認できた物件は、許可範囲内で確認済みの番地・建物名・部屋番号まで掲載できます。広告不可・未確認の預かり物件や承諾待ちの物件は非公開で管理します。物件チャットは公開用住所だけを回答し、非公開物件、REINS原資料、入居者情報、社内情報は取得できません。',
        action: '公開物件を確認する',
      },
      en: {
        title: 'Can I access a full address or private listings?',
        body: 'Listings with confirmed advertising permission may show verified street, building and unit details within the permitted scope. Entrusted properties without permission and properties awaiting consent remain private. Property chat answers from the approved public address only; private listings, REINS source documents, occupant details and internal information are unavailable.',
        action: 'View public listings',
      },
      'zh-TW': {
        title: '可以查看完整地址或非公開物件嗎？',
        body: '已確認廣告許可的物件，可在許可範圍內刊登經確認的門牌、建物名稱及房號。未獲廣告許可或等待同意的委託物件維持非公開。物件聊天只回答已核准公開的地址，無法取得非公開物件、REINS原始資料、住戶資料或內部資訊。',
        action: '查看公開物件',
      },
      'zh-CN': {
        title: '可以查看完整地址或非公开房源吗？',
        body: '已确认广告许可的房源，可在许可范围内刊登经确认的门牌、建筑名称及房号。未获广告许可或等待同意的委托房源保持非公开。房源聊天只回答已批准公开的地址，无法获取非公开房源、REINS原始资料、住户资料或内部信息。',
        action: '查看公开房源',
      },
    },
  },
  {
    id: 'price-and-availability',
    category: 'listing',
    href: '/buying-guide',
    keywords: [
      '価格',
      '値段',
      '費用',
      '諸費用',
      '販売',
      '売れ',
      '成約',
      'ローン',
      '融資',
      '民泊',
      '許可',
      '利回り',
      'price',
      'cost',
      'fee',
      'available',
      'availability',
      'sold',
      'loan',
      'mortgage',
      'minpaku',
      'license',
      'yield',
      '價格',
      '价格',
      '費用',
      '费用',
      '出售',
      '售出',
      '贷款',
      '貸款',
      '民宿',
      '许可',
      '許可',
    ],
    text: {
      ja: {
        title: '価格・販売状況・利用可否は確定情報ですか？',
        body: '掲載価格は物件の提示価格です。購入時の諸費用を含む総額ではありません。販売状況、価格交渉、融資、法的な利用可否や宿泊事業の許可は、自動回答では確定できません。購入判断の前に、その物件の問い合わせフォームから最新条件を確認してください。購入の流れは購入ガイドで案内しています。',
        action: '購入ガイドを読む',
      },
      en: {
        title: 'Are price, availability and permitted uses confirmed?',
        body: 'The listed price is the asking price, not the total purchase cost including fees. Automatic answers cannot confirm current availability, negotiations, financing, legally permitted uses or lodging permits. Before deciding to buy, ask for current terms through the property’s inquiry form. The buying guide explains the purchase process.',
        action: 'Read the buying guide',
      },
      'zh-TW': {
        title: '價格、出售狀態及用途已確認嗎？',
        body: '刊登價格為物件要價，不是包含購買費用的總額。自動回答無法確認最新出售狀態、議價、貸款、法定用途或住宿營業許可。購買決定前，請透過該物件的詢問表單確認最新條件。購買指南提供交易流程說明。',
        action: '閱讀購買指南',
      },
      'zh-CN': {
        title: '价格、出售状态及用途已确认吗？',
        body: '刊登价格为房产要价，不是包含购买费用的总额。自动回答无法确认最新出售状态、议价、贷款、法定用途或住宿营业许可。购买决定前，请通过该房产的咨询表单确认最新条件。购买指南提供交易流程说明。',
        action: '阅读购买指南',
      },
    },
  },
  {
    id: 'account',
    category: 'account',
    href: '/login',
    keywords: [
      'ログイン',
      '登録',
      'アカウント',
      'パスワード',
      'login',
      'log in',
      'sign in',
      'sign up',
      'register',
      'account',
      'password',
      '登入',
      '登录',
      '註冊',
      '注册',
      '帳號',
      '账号',
      '密碼',
      '密码',
    ],
    text: {
      ja: {
        title: 'ログインが必要なのはどの機能ですか？',
        body: '公開物件の閲覧、検索、ヘルプ、物件チャットはログインなしで使えます。お気に入りと物件問い合わせの送信にはログインが必要です。ログインページからログインでき、新規登録へのリンクもあります。ヘルプにパスワードや認証コードを入力しないでください。',
        action: 'ログインする',
      },
      en: {
        title: 'Which features require signing in?',
        body: 'Public listings, search, help and property chat work without signing in. Saving favorite properties and submitting property inquiries require an account. Use the login page, which also links to registration. Do not enter passwords or verification codes in help.',
        action: 'Sign in',
      },
      'zh-TW': {
        title: '哪些功能需要登入？',
        body: '公開物件、搜尋、幫助及物件聊天不必登入。收藏物件及提交物件詢問需要登入。登入頁也提供註冊連結。請勿在幫助輸入密碼或驗證碼。',
        action: '登入',
      },
      'zh-CN': {
        title: '哪些功能需要登录？',
        body: '公开房源、搜索、帮助及房产聊天不必登录。收藏房产及提交房产咨询需要登录。登录页也提供注册链接。请勿在帮助中输入密码或验证码。',
        action: '登录',
      },
    },
  },
]

const copy = {
  ja: {
    nav: 'ヘルプ',
    title: '探す前も、気になった後も。',
    subtitle: 'ポータルの使い方を、検索してすぐに確認できます。',
    assistant: 'ヘルプ検索・自動回答',
    note: 'ヘルプの掲載内容から回答します。生成AIは使わず、質問は外部AIへ送信しません。',
    placeholder: '例：検索条件を保存するには？',
    label: 'ヘルプへの質問・検索語',
    submit: '回答を表示',
    clear: 'クリア',
    sources: '回答の根拠',
    answer: '関連するヘルプからの回答',
    empty:
      '一致するヘルプが見つかりませんでした。言葉を変えて検索するか、下の項目をご覧ください。物件固有の質問は、物件ページのチャット・問い合わせをご利用ください。',
    results: '関連する項目',
    all: '使い方を調べる',
    categories: {
      search: '物件を探す',
      listing: '物件を確認・相談する',
      account: 'アカウント・表示設定',
    },
    privacy: 'パスワードや個人情報は入力しないでください。',
    browse: '物件一覧へ',
    guide: '購入ガイド',
    examples: [
      '駅から近い物件を探したい',
      '検索条件を保存するには？',
      '内見の相談をしたい',
    ],
    open: '詳しい手順を読む',
  },
  en: {
    nav: 'Help',
    title: 'From searching to your next step.',
    subtitle: 'Find clear answers about using the portal.',
    assistant: 'Help search & automatic answers',
    note: 'Answers come from published help. No generative AI is used and questions are not sent to an external AI service.',
    placeholder: 'For example: How do I save a search?',
    label: 'Question or help search term',
    submit: 'Show answer',
    clear: 'Clear',
    sources: 'Answer sources',
    answer: 'Answers from related help',
    empty:
      'No matching help was found. Try different words or browse the topics below. For a specific property, use chat or the inquiry form on its page.',
    results: 'Related topics',
    all: 'Explore the help topics',
    categories: {
      search: 'Find properties',
      listing: 'Understand & inquire',
      account: 'Account & language',
    },
    privacy: 'Do not enter passwords or personal information.',
    browse: 'Browse properties',
    guide: 'Buying guide',
    examples: [
      'Find a property near a station',
      'How do I save a search?',
      'How do I request a viewing?',
    ],
    open: 'Read the instructions',
  },
  'zh-TW': {
    nav: '幫助',
    title: '從搜尋到下一步，都有指引。',
    subtitle: '搜尋並立即了解平台的使用方式。',
    assistant: '幫助搜尋與自動回答',
    note: '根據已刊登的幫助內容回答。不使用生成式AI，也不會將問題傳送至外部AI服務。',
    placeholder: '例如：如何儲存搜尋條件？',
    label: '問題或搜尋關鍵字',
    submit: '顯示回答',
    clear: '清除',
    sources: '回答依據',
    answer: '來自相關幫助的回答',
    empty:
      '找不到相符內容。請換個關鍵字，或查看下方主題。個別物件問題請使用物件頁的聊天或詢問表單。',
    results: '相關主題',
    all: '查看使用指引',
    categories: {
      search: '尋找物件',
      listing: '了解及詢問物件',
      account: '帳號與語言',
    },
    privacy: '請勿輸入密碼或個人資料。',
    browse: '查看物件',
    guide: '購買指南',
    examples: ['想找靠近車站的物件', '如何儲存搜尋條件？', '如何預約看房？'],
    open: '閱讀詳細指引',
  },
  'zh-CN': {
    nav: '帮助',
    title: '从搜索到下一步，都有指引。',
    subtitle: '搜索并立即了解平台的使用方式。',
    assistant: '帮助搜索与自动回答',
    note: '根据已刊登的帮助内容回答。不使用生成式AI，也不会将问题发送至外部AI服务。',
    placeholder: '例如：如何保存搜索条件？',
    label: '问题或搜索关键词',
    submit: '显示回答',
    clear: '清除',
    sources: '回答依据',
    answer: '来自相关帮助的回答',
    empty:
      '找不到匹配内容。请换个关键词，或查看下方主题。单个房产问题请使用房产页的聊天或咨询表单。',
    results: '相关主题',
    all: '查看使用指引',
    categories: {
      search: '寻找房产',
      listing: '了解及咨询房产',
      account: '账号与语言',
    },
    privacy: '请勿输入密码或个人信息。',
    browse: '查看房产',
    guide: '购买指南',
    examples: ['想找靠近车站的房产', '如何保存搜索条件？', '如何预约看房？'],
    open: '阅读详细指引',
  },
}

export function helpLocale(locale: string): HelpLocale {
  return locale === 'ja' || locale === 'zh-TW' || locale === 'zh-CN'
    ? locale
    : 'en'
}
export function getHelpCopy(locale: string) {
  return copy[helpLocale(locale)]
}
