'use client'
import { useCallback,useEffect,useState,useRef } from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { createClient } from '@/lib/supabase/client'
import { useLocale } from 'next-intl'
import { criteriaSchema, types, type BuyerCriteria, type MatchFacts, type Evaluation } from '@/lib/buyer-matching-policy'
import { getBuyerMatchingCopy,describeCheck } from '@/lib/buyer-matching-copy'
import { getBuyerJourneyCopy } from '@/lib/buyer-journey-copy'
import { PropertyChatLink } from '@/components/chat/private-chats'
import { BuyerCriteriaForm } from './buyer-criteria-form'
import { getBuyerSearchCopy } from '@/lib/buyer-search-copy'
import { buyerSearchReturnPath, currentComparisonIds, toggleComparison } from '@/lib/buyer-search-ui'
import { translateCityName } from '@/lib/translate-fields'

type Profile={id:string;revision:number;criteria:BuyerCriteria;lastMatchedAt:string|null;lastSourceAt:string|null;sourceState:string}
type Suggestion={listingId:string;listing:MatchFacts&{address:string|null;image:string|null;lastSourceAt:string|null};evaluation:Evaluation;feedback:{rating:number|null;status:string;reason:string}|null;suggestedAt:string}
type Data={profile:Profile|null;recommendations:Suggestion[];incomplete:boolean;automationActive:boolean}
type FeedbackStatus='neutral'|'like'|'shortlist'|'dismiss'
const reasons=['none','price','area','size','occupancy','yield','condition','other'] as const
export function BuyerSearch({initialPurpose=''}:{initialPurpose?:string}){
  const locale=useLocale(),c=getBuyerMatchingCopy(locale),journey=getBuyerJourneyCopy(locale),ui=getBuyerSearchCopy(locale)
  const requestEpoch=useRef(0),sessionId=useRef<string|null|undefined>(undefined)
  const defaultCriteria=useCallback(()=>criteriaSchema.parse({purpose:['investment','land'].includes(initialPurpose)?initialPurpose:'residential'}),[initialPurpose])
  const clearPrivate=useCallback(()=>{requestEpoch.current++;setData(null);setCriteria(defaultCriteria());setSelected([]);setFeedbackReasons({});setDirty(false);setEditing(false);setShowOthers(false);setNotice('')},[defaultCriteria])
  const [criteria,setCriteria]=useState<BuyerCriteria>(()=>criteriaSchema.parse({purpose:['investment','land'].includes(initialPurpose)?initialPurpose:'residential'}))
  const [data,setData]=useState<Data|null>(null),[login,setLogin]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dirty,setDirty]=useState(false)
  const [selected,setSelected]=useState<string[]>([]),[showOthers,setShowOthers]=useState(false),[feedbackReasons,setFeedbackReasons]=useState<Record<string,string>>({})
  const [editing,setEditing]=useState(false)
  const money=(n:number|null,currency:string)=>{if(n===null)return c.unknown;try{return new Intl.NumberFormat(locale,{style:'currency',currency,maximumFractionDigits:0}).format(n)}catch{return c.unknown}}
  const date=(s:string|null)=>s?new Date(s).toLocaleString(locale):c.unknown
  const load=useCallback(async(replace=false)=>{
    const epoch=++requestEpoch.current
    if(replace)setLoading(true)
    try{const r=await fetch('/api/buyer/recommendations',{cache:'no-store'});if(epoch!==requestEpoch.current)return;if(r.status===401){clearPrivate();setLogin(true);setLoading(false);return}const v=await r.json();if(epoch!==requestEpoch.current)return;if(!r.ok)throw new Error(v.error);setLogin(false);setData(v);if(replace){setCriteria(v.profile?.criteria||defaultCriteria());setDirty(false);setEditing(false)}setError('')}
    catch{if(epoch===requestEpoch.current)setError(getBuyerMatchingCopy(locale).error)}finally{if(epoch===requestEpoch.current)setLoading(false)}
  },[locale,clearPrivate,defaultCriteria])
  useEffect(()=>{void load(true)},[load])
  useEffect(()=>{const {data:{subscription}}=createClient().auth.onAuthStateChange((event,session)=>{const next=session?.user.id||null;if(event==='SIGNED_OUT'||(sessionId.current!==undefined&&sessionId.current!==next)){clearPrivate();setLogin(!next);setLoading(false);if(next)void load(true)}sessionId.current=next});return()=>subscription.unsubscribe()},[clearPrivate,load])
  useEffect(()=>{if(login||dirty||busy||editing)return;const timer=setInterval(()=>{if(!document.hidden)void load()},60000);return()=>clearInterval(timer)},[load,login,dirty,busy,editing])
  function edit<K extends keyof BuyerCriteria>(key:K,value:BuyerCriteria[K]){setCriteria(old=>({...old,[key]:value}));setDirty(true);setNotice('')}
  async function save(){const epoch=requestEpoch.current;setBusy(true);setError('');try{const r=await fetch('/api/buyer/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:data?.profile?.id||null,revision:data?.profile?.revision||0,criteria})});if(epoch!==requestEpoch.current)return;if(r.status===401){clearPrivate();setLogin(true);setLoading(false);return}if(!r.ok)throw new Error(r.status===409?c.conflict:c.error);setDirty(false);setNotice(c.saved);await load(true)}catch(e){if(epoch===requestEpoch.current)setError((e as Error).message)}finally{setBusy(false)}}
  async function feedback(row:Suggestion,status:FeedbackStatus,rating:number|null){if(!data?.profile)return;const epoch=requestEpoch.current;setBusy(true);try{const r=await fetch('/api/buyer/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:data.profile.id,listingId:row.listingId,revision:data.profile.revision,status,rating,reason:feedbackReasons[row.listingId]||'none',nonce:crypto.randomUUID()})});if(epoch!==requestEpoch.current)return;if(!r.ok)throw new Error(r.status===409?c.conflict:c.error);await load(false)}catch(e){if(epoch===requestEpoch.current)setError((e as Error).message)}finally{setBusy(false)}}
  async function remove(){if(!data?.profile||!window.confirm(c.confirmRemove))return;const epoch=requestEpoch.current;setBusy(true);try{const r=await fetch('/api/buyer/profile',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:data.profile.id,revision:data.profile.revision})});if(epoch!==requestEpoch.current)return;if(!r.ok)throw new Error(c.error);setSelected([]);setDirty(false);await load(true)}catch{if(epoch===requestEpoch.current)setError(c.error)}finally{setBusy(false)}}
  const recommendations=data?.recommendations||[],availableIds=recommendations.map(x=>x.listingId),comparisonIds=currentComparisonIds(selected,availableIds),comparison=recommendations.filter(x=>comparisonIds.includes(x.listingId))
  const editorOpen=!data?.profile||editing||dirty
  const returnPath=buyerSearchReturnPath(initialPurpose)
  const saved=data?.profile?.criteria
  return <section data-testid="buyer-search" className="border-t-2 border-[#274d7d] pt-8">
    <h2 className="text-2xl font-semibold">{c.title}</h2><p className="my-4 leading-7 text-[#657487]">{c.intro}</p><p className="mb-6 text-sm text-[#657487]">{c.privacy}</p>
    {loading&&<p role="status">{c.loading}</p>}{error&&<p role="alert" className="mb-5 rounded border border-red-300 bg-red-50 p-3">{error}</p>}{notice&&<p role="status" className="mb-5 text-green-800">{notice}</p>}
    {login&&<div className="rounded-xl border bg-[#f1f6fb] p-5 sm:p-8" data-testid="buyer-onboarding"><h3 className="text-xl font-semibold">{ui.start}</h3><p className="mt-3 leading-7 text-[#657487]">{ui.startNote}</p><ol className="my-6 grid gap-4 sm:grid-cols-3">{ui.steps.map((step,i)=><li className="flex items-start gap-3 text-sm" key={step}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#274d7d] text-white">{i+1}</span><span className="pt-1">{step}</span></li>)}</ol><div className="flex flex-wrap gap-3"><Link className="rounded-lg bg-[#274d7d] px-5 py-3 font-semibold text-white" href={`/register?redirect=${encodeURIComponent(returnPath)}`}>{ui.register}</Link><Link className="rounded-lg border border-[#274d7d] bg-white px-5 py-3 text-[#274d7d]" href={`/login?redirect=${encodeURIComponent(returnPath)}`}>{c.login}</Link></div><Link className="mt-5 inline-block py-2 text-sm underline" href="/listings">{ui.browse}</Link></div>}
    {!login&&!loading&&data&&<>
      {saved&&<div className="mb-6 rounded-xl border bg-[#f8fafc] p-5" data-testid="buyer-saved-criteria"><h3 className="font-semibold">{ui.savedCriteria}</h3><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-[#657487]">{journey.purpose}</dt><dd className="mt-1 font-medium">{journey.purposeOptions[['investment','residential','land'].indexOf(saved.purpose)]}</dd></div><div><dt className="text-[#657487]">{c.keys.budget}</dt><dd className="mt-1 font-medium">{saved.budgetMin===null&&saved.budgetMax===null?c.any:`${saved.budgetMin===null?c.any:money(saved.budgetMin,'JPY')} – ${saved.budgetMax===null?c.any:money(saved.budgetMax,'JPY')}`}</dd></div><div><dt className="text-[#657487]">{c.keys.area}</dt><dd className="mt-1 font-medium">{saved.wards.length?saved.wards.map(w=>translateCityName(w,locale)||w).join(' · '):c.any}</dd></div><div><dt className="text-[#657487]">{journey.type}</dt><dd className="mt-1 font-medium">{saved.propertyTypes.length?saved.propertyTypes.map(t=>journey.typeOptions[types.indexOf(t)]).join(' · '):c.any}</dd></div></dl><div className="mt-5 flex flex-wrap gap-3"><button type="button" className="min-h-11 rounded-lg border bg-white px-4 py-2" disabled={busy||loading||editorOpen} onClick={()=>setEditing(true)} aria-controls="buyer-criteria-editor" aria-expanded={editorOpen}>{ui.edit}</button><button type="button" className="min-h-11 rounded-lg border bg-white px-4 py-2" disabled={busy||dirty||loading||editing} onClick={()=>void load(true)}>{c.refresh}</button></div></div>}
      {editorOpen&&<form id="buyer-criteria-editor" onSubmit={e=>{e.preventDefault();void save()}} className="space-y-6 rounded-xl border p-5 sm:p-6" data-testid="buyer-criteria-editor">
        <BuyerCriteriaForm locale={locale} criteria={criteria} disabled={busy||loading} onChange={edit}/>
        <div className="flex flex-wrap gap-3"><button disabled={busy||loading} className="min-h-11 rounded-lg bg-[#274d7d] px-5 py-3 font-semibold text-white disabled:opacity-50" type="submit">{busy?c.loading:c.save}</button>{saved&&<button type="button" className="min-h-11 rounded-lg border px-4 py-3" disabled={busy||loading} onClick={()=>{setCriteria(saved);setDirty(false);setEditing(false);setError('');setNotice('')}}>{ui.cancel}</button>}</div>
      </form>}
    </>}
    {data?.profile&&<div className="my-8 rounded-lg border bg-[#f8fafc] p-5 text-sm"><p>{c.last}：{date(data.profile.lastMatchedAt)}</p><p className="mt-2">{c.source}：{c.sourceStates[['waiting','acquiring','review_pending','failed'].indexOf(data.profile.sourceState)]||c.unknown}{data.profile.lastSourceAt?` · ${date(data.profile.lastSourceAt)}`:''}</p>{(!data.profile.criteria.active||!data.automationActive)&&<p className="mt-3">{c.paused}</p>}{data.incomplete&&<p className="mt-3">{c.partial}</p>}<button disabled={busy||loading} className="mt-5 text-[#657487] underline" onClick={()=>void remove()}>{c.remove}</button></div>}
    {comparison.length>0&&<section id="buyer-comparison" className="my-8 scroll-mt-44" data-testid="buyer-comparison"><h3 className="mb-4 text-xl font-semibold">{c.comparison}</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th></th>{comparison.map(r=><th className="min-w-40 border p-3" key={r.listingId}><Link href={`/listings/${r.listingId}`}>{r.listing.address||r.listing.city||r.listing.propertyType}</Link></th>)}</tr></thead><tbody>{[[c.price,(r:Suggestion)=>money(r.listing.price,r.listing.priceCurrency)],[c.size,(r:Suggestion)=>`${(r.listing.propertyType==='土地'?r.listing.landArea:r.listing.buildingArea)??c.unknown} ㎡`],[c.status,(r:Suggestion)=>r.listing.currentStatus||c.unknown],[c.built,(r:Suggestion)=>r.listing.builtYear??c.unknown],[c.gross,(r:Suggestion)=>r.listing.yieldGross===null?c.unknown:`${r.listing.yieldGross}%`],[c.cost,()=>c.unknown]].map(([label,value],i)=><tr key={i}><th className="border p-3">{String(label)}</th>{comparison.map(r=><td className="border p-3" key={r.listingId}>{(value as (r:Suggestion)=>string|number)(r)}</td>)}</tr>)}</tbody></table></div></section>}
    {data?.profile&&<><h3 className="mt-8 text-xl font-semibold">{ui.suggestions}</h3><label className="my-6 flex items-center gap-2 text-sm"><input type="checkbox" checked={showOthers} onChange={e=>setShowOthers(e.target.checked)}/>{c.others}</label>{recommendations.filter(r=>showOthers||r.evaluation.status!=='outside').length===0&&<p className="my-8 rounded border p-6 text-[#657487]">{c.empty}</p>}</>}
    <div className="space-y-6">{recommendations.filter(r=>showOthers||r.evaluation.status!=='outside').map(row=><article key={row.listingId} className="rounded-lg border bg-white p-5" data-testid="buyer-suggestion">
      <div className="flex flex-wrap gap-5">{row.listing.image&&<Image width={224} height={160} unoptimized className="h-40 w-56 rounded object-cover" src={row.listing.image} alt={row.listing.address||row.listing.city||row.listing.propertyType||c.details}/>}<div className="min-w-0 flex-1"><span className="text-sm font-medium text-[#57769b]">{c[row.evaluation.status]} · {c.score} {row.evaluation.score}/100</span><h3 className="mt-2 text-xl font-semibold"><Link href={`/listings/${row.listingId}`}>{row.listing.address||row.listing.city||row.listing.propertyType}</Link></h3><p className="mt-3 text-xl font-semibold">{money(row.listing.price,row.listing.priceCurrency)}</p><p className="mt-2 text-sm">{c.status}：{row.listing.currentStatus||c.unknown} · {c.size}：{(row.listing.propertyType==='土地'?row.listing.landArea:row.listing.buildingArea)??c.unknown}㎡</p><p className="mt-2 text-xs text-[#657487]">{c.captured}：{date(row.listing.lastSourceAt)}</p></div></div>
      <h4 className="mb-2 mt-5 font-semibold">{c.why}</h4><ul className="space-y-1 text-sm">{row.evaluation.checks.map(check=><li key={check.key} className={check.result==='miss'?'text-amber-800':''}>{describeCheck(check,locale)}</li>)}</ul>{row.evaluation.preferenceBonus>0&&<p className="mt-3 text-sm">{c.preference}</p>}
      <h4 className="mb-2 mt-5 font-semibold">{c.unconfirmed}</h4><ul className="space-y-1 text-sm text-[#657487]">{row.evaluation.unconfirmed.map(key=><li key={key}>{c.unknowns[key as keyof typeof c.unknowns]||key}</li>)}</ul><p className="mt-3 text-xs text-[#657487]">{c.cost} {c.sourceNote}</p>
      <div className="mt-5 flex flex-wrap items-center gap-3"><button disabled={busy||dirty||loading} onClick={()=>void feedback(row,'like',5)} className="rounded border px-4 py-2">{row.feedback?.status==='like'?'♥ ':''}{c.like}</button><label className="text-sm">{c.reason} <select className="rounded border p-2" value={feedbackReasons[row.listingId]||'none'} onChange={e=>setFeedbackReasons(old=>({...old,[row.listingId]:e.target.value}))}>{reasons.map((reason,i)=><option key={reason} value={reason}>{c.reasons[i]}</option>)}</select></label><button disabled={busy||dirty||loading} className="rounded border px-4 py-2" onClick={()=>void feedback(row,'dismiss',1)}>{c.dismiss}</button><label className="flex gap-2 text-sm"><input type="checkbox" disabled={!comparisonIds.includes(row.listingId)&&comparisonIds.length>=3} checked={comparisonIds.includes(row.listingId)} onChange={e=>setSelected(old=>toggleComparison(old,availableIds,row.listingId,e.target.checked))}/>{c.compare}</label><Link href={`/listings/${row.listingId}`} className="text-sm underline">{c.details}</Link></div>
      <div className="mt-4 max-w-sm"><PropertyChatLink listingId={row.listingId}/></div>
    </article>)}</div>
    {comparison.length>0&&<div className="sticky bottom-3 z-10 mt-6 flex flex-wrap items-center gap-3 rounded-xl border bg-white p-4 shadow-lg" data-testid="buyer-comparison-tray"><span className="text-sm">{ui.selected}: {comparison.length} / 3</span><Link className="min-h-11 rounded-lg bg-[#274d7d] px-4 py-3 text-sm font-semibold text-white" href="#buyer-comparison">{ui.compareNow}</Link><button className="min-h-11 rounded-lg border px-4 py-2 text-sm" type="button" onClick={()=>setSelected([])}>{ui.clear}</button></div>}
  </section>
}
